// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB10b4SojHiasE1rbl16TyBjRl2yM4D1Ds',
    appId: '1:480196148532:web:6eacabcb9bb63c121d3961',
    messagingSenderId: '480196148532',
    projectId: 'current-mode',
    authDomain: 'current-mode.firebaseapp.com',
    storageBucket: 'current-mode.firebasestorage.app',
    measurementId: 'G-Q92H09G0CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-H525jNYzG9QRkFa5p6vWvM0wef35uo',
    appId: '1:480196148532:android:dca7bbd7e0afcdfc1d3961',
    messagingSenderId: '480196148532',
    projectId: 'current-mode',
    storageBucket: 'current-mode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZCQOJY6LT7QzoKkvfOtniV-8jQmSSiY',
    appId: '1:480196148532:ios:eacd3f52fbfdcdcb1d3961',
    messagingSenderId: '480196148532',
    projectId: 'current-mode',
    storageBucket: 'current-mode.firebasestorage.app',
    iosClientId: '480196148532-t9m509fi2p9ovi5a9ljcdlua0ig1d754.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoZCQOJY6LT7QzoKkvfOtniV-8jQmSSiY',
    appId: '1:480196148532:ios:eacd3f52fbfdcdcb1d3961',
    messagingSenderId: '480196148532',
    projectId: 'current-mode',
    storageBucket: 'current-mode.firebasestorage.app',
    iosClientId: '480196148532-t9m509fi2p9ovi5a9ljcdlua0ig1d754.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB10b4SojHiasE1rbl16TyBjRl2yM4D1Ds',
    appId: '1:480196148532:web:569fe8f71f75fa891d3961',
    messagingSenderId: '480196148532',
    projectId: 'current-mode',
    authDomain: 'current-mode.firebaseapp.com',
    storageBucket: 'current-mode.firebasestorage.app',
    measurementId: 'G-RQNEM0PXJS',
  );

}